# wrangler.toml
name = "b2b-website"
main = "./dist/server/index.js"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "./dist"

[env.production]
name = "b2b-website"
routes = [
    { pattern = "https://b2b-website-31t.pages.dev/*", zone_name = "pages.dev" }
]

[site]
bucket = "./dist/client"