{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "b2b-website",
  "main": "./dist/server/index.js",
  "compatibility_date": "2026-04-11",
  "compatibility_flags": ["nodejs_compat"],
  "assets": {
    "directory": "./dist"
  }
}